### ISSUE TITLE
test new sparkline?

### ISSUE THREAD

**Issue by timelyportfolio** [Yang-Tang/sparklinePlateMod#1]
I just discovered your package and noticed that it relies on `sparkline`.  Would you mind testing the newest version on Github to make sure it still works as expected in your package?  Thanks!

**Comment by Yang-Tang** [comment]
@timelyportfolio The current version of `sparkline` is working very well in this package. It's great to learn the `sparkline` package will be on CRAN. Thank you for your effort!
